name: Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Ha van npm dependency, másképp lehet buildelni is.

      - name: Build project
        run: npm run build

      - name: Check asset-manifest.json
        run: cat ./build/asset-manifest.json

      - name: Upload to Itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: './build'
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: vdcoderforfun
          game: 'feed-the-mouse'
          channel: 'html5'